//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ControlPlc
    {
        public Nullable<int> TakeMaterialX { get; set; }
        public Nullable<int> TakeMaterialY { get; set; }
        public Nullable<int> PutMaterialX { get; set; }
        public Nullable<int> PutMaterialY { get; set; }
        public Nullable<int> LoadHeight { get; set; }
        public Nullable<int> note { get; set; }
        public Nullable<int> Array { get; set; }
        public int ID { get; set; }
    }
}
