//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hous
    {
        public string Category { get; set; }
        public string Name { get; set; }
        public string PartName { get; set; }
        public string PartSpec { get; set; }
        public Nullable<double> StockQTY { get; set; }
        public int ID { get; set; }
        public Nullable<int> z { get; set; }
        public string PartMaterial { get; set; }
        public int hid { get; set; }
        public int aid { get; set; }
        public int gid { get; set; }
        public string height { get; set; }
        public string Type { get; set; }
        public Nullable<int> mid { get; set; }
    }
}
