//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrder
    {
        public int ID { get; set; }
        public string PO { get; set; }
        public Nullable<int> MaterialID { get; set; }
        public Nullable<double> QTY { get; set; }
        public string Units { get; set; }
        public Nullable<int> ApplierID { get; set; }
        public Nullable<int> StatusID { get; set; }
    }
}
