//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WCS_Comm
    {
        public string AID { get; set; }
        public string CID { get; set; }
        public string Name { get; set; }
        public Nullable<int> qx { get; set; }
        public Nullable<int> qy { get; set; }
        public Nullable<int> fx { get; set; }
        public Nullable<int> fy { get; set; }
        public Nullable<double> InQTY { get; set; }
        public string Statu { get; set; }
        public string IP { get; set; }
        public string pname { get; set; }
        public string gname { get; set; }
    }
}
