//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WH_Comm
    {
        public string aid { get; set; }
        public string mid { get; set; }
        public string PartName { get; set; }
        public string PartSpec { get; set; }
        public string PartMaterial { get; set; }
        public Nullable<double> QTY { get; set; }
        public string Units { get; set; }
        public int PalletQTY { get; set; }
        public string Name { get; set; }
        public string type { get; set; }
        public string Status { get; set; }
        public Nullable<int> FromID { get; set; }
        public Nullable<int> ToID { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public string cl { get; set; }
    }
}
